name: ajoutée un mod 
description: Show off your Eleventy site on the Eleventy documentation
title: "[mod]__votre nom de mod__"
labels: mod
body:
  - type: markdown
    attributes:
      value: |
        Only the site URL is required. All other fields are optional.
  - type: input
    id: url
    attributes:
      label: URL du site
      description: l'url de la page d'accueil 
      placeholder: par exemple https://www.zachleat.com/
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Nom du mod
      description: le nom de votre mod 
      placeholder: par exemple Zach's Mod
    validations:
      required: true
  - type: input
    id: download_link
    attributes:
      label: Lien de téléchargement
      description: L'URL pour télécharger votre mod. _[parser:url]_
      placeholder: par exemple https://example.com/download
    validations:
      required: true
  - type: textarea
    id: authors
    attributes:
      label: Auteurs (noms d'utilisateur GitHub)
      description: Facultatif : _Laissez ce champ vide si vous êtes le seul auteur._ Si vous énumérez un ou plusieurs autres auteurs, assurez-vous d'inclure vous-même dans cette liste ! _[parser:usernames]_
      placeholder: par exemple @zachleat, @pdehaan
    validations:
      required: false